/-
# MiniSpinGeometry: Core Basic Definitions

L1: Clifford algebra Cl(n), Spin group, Spinors.
L2: Pauli matrices, spin representations.
L6: #eval verification of Pauli and Clifford relations.
-/

import MiniObjectKernel.Core.Basic

namespace MiniSpinGeometry

/-! ## L1: Signature Type

A signature (p,q) specifies the quadratic form:
  Q(x) = -x1^2 - ... - xp^2 + x_{p+1}^2 + ... + x_{p+q}^2
-/

structure Signature where
  p : Nat
  q : Nat
  deriving BEq, Repr, Inhabited

def Signature.totalDim (s : Signature) : Nat := s.p + s.q
def Signature.negDef (n : Nat) : Signature := { p := n, q := 0 }
def Signature.posDef (n : Nat) : Signature := { p := 0, q := n }
def Signature.minkowski : Signature := { p := 1, q := 3 }

/-! ## L1: Clifford Algebra Cl(n)

Generated by e_0,...,e_{n-1} with e_i^2 = -1, e_i e_j = -e_j e_i (i!=j).
We represent elements abstractly as formal linear combinations.
-/

inductive CliffordTerm (n : Nat) : Type where
  | scalar : Int -> CliffordTerm n
  | generator : Nat -> CliffordTerm n
  | product : CliffordTerm n -> CliffordTerm n -> CliffordTerm n
  deriving Repr, Inhabited

abbrev CliffordNumber (n : Nat) := CliffordTerm n

namespace CliffordNumber

def zero {n : Nat} : CliffordNumber n := CliffordTerm.scalar 0
def one {n : Nat} : CliffordNumber n := CliffordTerm.scalar 1
def scalar {n : Nat} (a : Int) : CliffordNumber n := CliffordTerm.scalar a
def basisVec {n : Nat} (i : Nat) (_h : i < n) : CliffordNumber n := CliffordTerm.generator i
def mul {n : Nat} (x y : CliffordNumber n) : CliffordNumber n := CliffordTerm.product x y

instance {n : Nat} : OfNat (CliffordNumber n) (nat_lit 0) where
  ofNat := zero

instance {n : Nat} : OfNat (CliffordNumber n) (nat_lit 1) where
  ofNat := one

end CliffordNumber

/-! ## L2: Spin Group Spin(n)

Spin(n) is the double cover of SO(n). For n>=3 it's the universal cover.
-/

structure SpinElement (n : Nat) where
  element : CliffordNumber n
  isEven : Bool := true
  isUnitary : Bool := true
  deriving Repr

def spinMul {n : Nat} (a b : SpinElement n) : SpinElement n :=
  { element := CliffordNumber.mul a.element b.element }

def spinOne {n : Nat} : SpinElement n :=
  { element := CliffordNumber.scalar 1 }

/-! ## L2: Spinor Space

Dimension 2^{floor(n/2)}. Splits into chiral halves for even n.
-/

structure Spinor (n : Nat) where
  components : List Int
  dim_ok : components.length = 2 ^ (n / 2)
  deriving Repr

def spinorDim (n : Nat) : Nat := 2 ^ (n / 2)

def spinorZero (n : Nat) : Spinor n :=
  { components := List.replicate (spinorDim n) 0
    dim_ok := by simp [spinorDim]
  }

/-! ## L1: Pauli Matrices

Fundamental 2x2 matrices: sigma_i with {sigma_i, sigma_j} = 2*delta_ij*I.
-/

def pauli1 : List (List Int) := [[0,1],[1,0]]
def pauli2 : List (List Int) := [[0,-1],[1,0]]
def pauli3 : List (List Int) := [[1,0],[0,-1]]
def identity2x2 : List (List Int) := [[1,0],[0,1]]

/-- Helper: get element (i,j) from a 2x2 matrix list. -/
def matGet (m : List (List Int)) (i j : Nat) : Int :=
  match m.get? i with
  | some row => match row.get? j with
    | some v => v
    | none => 0
  | none => 0

/-- 2x2 matrix multiplication. -/
def matMul2x2 (a b : List (List Int)) : List (List Int) :=
  let a00 := matGet a 0 0; let a01 := matGet a 0 1
  let a10 := matGet a 1 0; let a11 := matGet a 1 1
  let b00 := matGet b 0 0; let b01 := matGet b 0 1
  let b10 := matGet b 1 0; let b11 := matGet b 1 1
  [[a00*b00 + a01*b10, a00*b01 + a01*b11],
   [a10*b00 + a11*b10, a10*b01 + a11*b11]]

def checkSigma1Sq : Bool := matMul2x2 pauli1 pauli1 == identity2x2
def negIdentity2x2 : List (List Int) := [[-1,0],[0,-1]]
def checkSigma2Sq : Bool := matMul2x2 pauli2 pauli2 == negIdentity2x2
def checkSigma3Sq : Bool := matMul2x2 pauli3 pauli3 == identity2x2

def checkSigma12Anti : Bool :=
  let a := matMul2x2 pauli1 pauli2
  let b := matMul2x2 pauli2 pauli1
  let s00 := matGet a 0 0 + matGet b 0 0
  let s01 := matGet a 0 1 + matGet b 0 1
  let s10 := matGet a 1 0 + matGet b 1 0
  let s11 := matGet a 1 1 + matGet b 1 1
  s00 == 0 && s01 == 0 && s10 == 0 && s11 == 0

/-! ## L1: Cl(1) = C, Cl^0(3) = H

Cl(1) has generator e with e^2 = -1, isomorphic to complex numbers.
Cl^0(3) (even subalgebra) is isomorphic to quaternions H.
-/

/-- Cl(1) multiplication: (a+be)(c+de) = (ac-bd) + (ad+bc)e. -/
def cl1Mul (a b c d : Int) : Int × Int :=
  (a*c - b*d, a*d + b*c)

/-- Quaternion multiplication for Cl^0(3) = H. -/
def quatMul (a b c d : Int) (p q r s : Int) : Int × Int × Int × Int :=
  (a*p - b*q - c*r - d*s,
   a*q + b*p + c*s - d*r,
   a*r - b*s + c*p + d*q,
   a*s + b*r - c*q + d*p)

/-! ## L1: Spin Representation Generators

For Spin(3) = SU(2), the spin representation generators are:
  S_i = (i/2) * sigma_i  (i=1,2,3)

They satisfy [S_i, S_j] = i * epsilon_{ijk} * S_k.
-/

/-- Compute the commutator [sigma_i, sigma_j] for Pauli matrices. -/
def pauliCommutator (i j : Nat) : List (List Int) :=
  let sigmas := [pauli1, pauli2, pauli3]
  let si := sigmas.get? i |>.getD [[0,0],[0,0]]
  let sj := sigmas.get? j |>.getD [[0,0],[0,0]]
  let prod1 := matMul2x2 si sj
  let prod2 := matMul2x2 sj si
  [[matGet prod1 0 0 - matGet prod2 0 0,
    matGet prod1 0 1 - matGet prod2 0 1],
   [matGet prod1 1 0 - matGet prod2 1 0,
    matGet prod1 1 1 - matGet prod2 1 1]]

/-! ## L6: #eval Verification
-/

#eval "=== MiniSpinGeometry Core.Basic ==="
#eval "Clifford algebra Cl(n): abstract definition"
#eval "Spin group Spin(n): double cover of SO(n)"
#eval "Spinor space: dim = 2^{floor(n/2)}"

#eval "sigma1:" ++ toString pauli1
#eval "sigma1^2 == I: " ++ toString checkSigma1Sq
#eval "sigma2^2 == I: " ++ toString checkSigma2Sq
#eval "sigma3^2 == I: " ++ toString checkSigma3Sq
#eval "sigma1*sigma2 + sigma2*sigma1 == 0: " ++ toString checkSigma12Anti

#eval "Cl(1) (1+2e)*(3+4e): " ++
  let (r,i) := cl1Mul 1 2 3 4
  s!"({r}) + ({i})*e"

#eval "Quaternion i*j: " ++
  let (w,x,y,z) := quatMul 0 1 0 0 0 0 1 0
  toString (s!"({w},{x},{y},{z})")

#eval "Quaternion i^2: " ++
  let (w,x,y,z) := quatMul 0 1 0 0 0 1 0 0
  toString (w == -1 && x == 0 && y == 0 && z == 0)

#eval "Spinor dimension n=3: " ++ toString (spinorDim 3)
#eval "Spinor dimension n=4: " ++ toString (spinorDim 4)

end MiniSpinGeometry
