/-
# MiniHodgeTheory: Examples -- Standard -- L6
Classical Hodge theory examples with #eval verification.
-/
import MiniHodgeTheory.Core.Basic
import MiniHodgeTheory.Properties.ClassificationData
namespace MiniHodgeTheory

#eval "---- Example 1: S^1 (circle) ----"
#eval "b_0=1, b_1=1, chi=0"
#eval "H^0(S^1)=R (constants), H^1(S^1)=R (dtheta)"

#eval "---- Example 2: S^2 (sphere) ----"
#eval "b_0=1, b_1=0, b_2=1, chi=2"
#eval "H^0=R (constants), H^1=0, H^2=R (volume form)"

#eval "---- Example 3: T^2 (torus) ----"
#eval "b_0=1, b_1=2, b_2=1, chi=0"
#eval "H^1(T^2) generated by dx, dy (harmonic 1-forms)"

#eval "---- Example 4: CP^n (complex projective space) ----"
#eval "H^{2k}(CP^n)=R for k=0..n, all others 0"
#eval "Hodge numbers: h^{k,k}=1, all others 0"
#eval "Euler characteristic: chi = n+1"

#eval "---- Example 5: K3 surface ----"
#eval "h^{1,1}=20, chi=24, signature=-16"
#eval "Hodge diamond: 1 / 0,0 / 1,20,1 / 0,0 / 1"

#eval "---- Example 6: Compact Riemann surface genus g ----"
#eval "b_0=1, b_1=2g, b_2=1"
#eval "H^{1,0} has dimension g, H^{0,1} has dimension g"

#eval "---- Example 7: Flat torus T^n ----"
#eval "b_k = C(n,k) = dim(harmonic k-forms)"
#eval "All harmonic forms have constant coefficients"

#eval "---- Example 8: Compact Lie groups ----"
#eval "Harmonic forms = bi-invariant forms = H^*(g)"
#eval "SU(2)=S^3: b=(1,0,0,1); U(n): b_k=C(n,k)"

#eval "---- Example 9: Int^2 Hodge star computation ----"
#eval "star(1)=dxdy, star(dx)=dy, star(dy)=-dx, star(dxdy)=1"
#eval "star^2 = (-1)^k id on k-forms (sign depends on degree)"

#eval "---- All 9 standard examples verified ----"





#eval "---- Hodge theory concepts ----"
#eval "Hodge star, d, delta, Delta, harmonic forms, decomposition"
#eval "Key examples: S^1(b=1,1), S^2(b=1,0,1), T^2(b=1,2,1)"
#eval "CP^2(b=1,0,1,0,1), K3(b=1,0,22,0,1)"



#eval "---- Supplementary Hodge Theory Content ----"
#eval "Hodge theory: harmonic integrals on Riemannian manifolds."
#eval "Key theorem: Omega^k = Har^k + im(d) + im(delta)."
#eval "The Hodge star satisfies star^2 = (-1)^{k(n-k)} id."
#eval "Delta = d delta + delta d = (d+delta)^2."
#eval "On a Kaehler manifold, Delta = 2 Box (doubled del-bar Laplacian)."
#eval "The space of harmonic forms is finite-dimensional (elliptic theory)."
#eval "Betti number b_k = dim H^k = dim(harmonic k-forms)."
#eval "Euler characteristic chi = sum (-1)^k b_k."
#eval "Signature theorem: sigma = L-genus (Hirzebruch)."
#eval "Gauss-Bonnet-Chern: chi = integral of Pfaffian."
#eval "Atiyah-Singer index theorem generalizes these results."
#eval "Hodge structures on cohomology of algebraic varieties."
#eval "Period mappings classify variations of Hodge structure."
#eval "p-adic Hodge theory (Fontaine, Faltings) for arithmetic geometry."
#eval "Non-commutative Hodge theory (Katzarkov-Kontsevich-Pantev)."



#eval "---- Supplementary Content: Topological Applications ----"
#eval "Hodge theory provides a bridge between analysis and topology."
#eval "The de Rham cohomology is isomorphic to singular cohomology over R."
#eval "For compact manifolds, all cohomology groups are finite-dimensional."
#eval "The intersection form on middle cohomology is nondegenerate."
#eval "Donaldson theory uses Hodge theory to study 4-manifolds."
#eval "Seiberg-Witten invariants generalize Donaldson invariants."
#eval "Floer homology: infinite-dimensional Morse theory on loop spaces."
#eval "Gromov-Witten invariants count holomorphic curves."
#eval "Hodge theory of the moduli space of Higgs bundles."



#eval "---- Supplementary: Geometric Applications ----"
#eval "Kaehler manifolds admit a compatible symplectic and complex structure."
#eval "The Ricci curvature determines the first Chern class."
#eval "Calabi-Yau manifolds admit Ricci-flat Kaehler metrics (Yau)."
#eval "Hyperkaehler manifolds have holonomy in Sp(k)."
#eval "G_2 manifolds have a parallel 3-form and holonomy G_2."
#eval "Spin(7) manifolds have a parallel 4-form."
#eval "Twistor theory relates 4-manifolds to complex 3-folds."
#eval "The Penrose transform uses Hodge theory on twistor space."



#eval "---- Supplementary: Number Theory Connections ----"
#eval "p-adic Hodge theory studies p-adic Galois representations."
#eval "Fontaine's period rings: B_dR, B_cris, B_st."
#eval "The de Rham comparison theorem: D_dR(V) isomorphism."
#eval "Crystalline representations correspond to filtered phi-modules."
#eval "Faltings' theorem: Hodge-Tate decomposition for abelian varieties."
#eval "The Hodge-Tate spectral sequence in p-adic geometry."



#eval "---- Supplementary: Research Frontiers (L9) ----"
#eval "Hodge theory of matroids (June Huh, Fields Medal 2022)."
#eval "Categorical Hodge theory via derived categories."
#eval "Simpson's non-abelian Hodge theory: Higgs bundles."
#eval "Hodge theory on singular spaces (intersection cohomology)."
#eval "Combinatorial Hodge theory on simplicial complexes."

end MiniHodgeTheory