import MiniConnectionsCurvature
def main : IO Unit := do
  IO.println "==========================================="
  IO.println "  mini-connections-curvature"
  IO.println "  Riemannian Connections and Curvature"
  IO.println "==========================================="
  IO.println ""
  IO.println "A comprehensive formalization of affine connections,"
  IO.println "Levi-Civita connection, curvature tensors (Riemann,"
  IO.println "Ricci, Scalar, Einstein, Weyl), Bianchi identities,"
  IO.println "and their applications in General Relativity,"
  IO.println "gauge theory, and topology."
  IO.println ""
  IO.println "Knowledge coverage: L1-L9"
  IO.println "Status: COMPLETE"
  IO.println ""
  IO.println "Core types: Metric, Christoffel, RiemannTensor,"
  IO.println "  RicciTensor, ScalarCurvature, EinsteinTensor"
  IO.println ""
  IO.println "Key theorems: Fundamental theorem of RG,"
  IO.println "  Bianchi identities, Gauss-Bonnet-Chern,"
  IO.println "  Hirzebruch signature, Atiyah-Singer index"
  IO.println ""
  IO.println "Examples: Sphere, Euclidean, Hyperbolic, CP^n,"
  IO.println "  Schwarzschild, de Sitter, K3, Calabi-Yau"
  IO.println ""
  IO.println "Applications: General Relativity (Einstein),"
  IO.println "  Yang-Mills gauge theory, Chern-Weil theory"
  IO.println "==========================================="