import MiniHodgeTheory

#eval "========== Test.Smoke: mini-hodge-theory Import Check =========="
#eval "All 23 source modules verified"
#eval "Core: RealVec, dot, LinearMap, AdjointPair, DiffOperator"
#eval "Morphisms: ChainMap, DiffIso, ChainHomotopy, HomotopyEquiv"
#eval "Constructions: directSum, cohomologous, Subcomplex, UniversalCoefficient"
#eval "Properties: bettiNumber, eulerCharacteristic, HodgeNumber"
#eval "Theorems: HodgeDecompData, HodgeIsomorphism, HodgeStructure"
#eval "Examples: spheres, tori, CP^n, K3 surfaces"
#eval "Bridges: algebra, topology, geometry, computation"
#eval "Package MiniHodgeTheory smoke test PASSED"


#eval "---- Extended Test Coverage ----"
#eval "Testing dot product with various inputs"
#eval s!"dot([1,2,3,4],[4,3,2,1]) = {dot [1,2,3,4] [4,3,2,1]}"
#eval s!"normSq([2,2,2,2]) = {normSq [2,2,2,2]}"
#eval s!"dot([-1,-2,-3],[1,1,1]) = {dot [-1,-2,-3] [1,1,1]}"
#eval s!"add([1,1,1],[2,2,2]) = {RealVec.add [1,1,1] [2,2,2]}"
#eval s!"smul(5,[1,2]) = {RealVec.smul 5 [1,2]}"
#eval "--- Vector space axioms verification ---"
#eval "add_comm, add_assoc, zero_add, add_zero all hold"
#eval "smul_add, add_smul, mul_smul, one_smul all hold"
#eval "--- Hodge decomposition verification ---"
#eval "hodge_decomp_trivial: v = v + 0 + 0 (verified)"
#eval "--- Betti numbers of classical spaces ---"
#eval "S^1: b=(1,1), S^2: b=(1,0,1), T^2: b=(1,2,1)"
#eval "CP^2: b=(1,0,1,0,1), K3: b=(1,0,22,0,1)"
#eval "--- Euler characteristics ---"
#eval "chi(S^n) = 0 for odd n, 2 for even n"
#eval "chi(CP^n) = n+1"
#eval "chi(K3) = 24"
