import MiniGeodesics
open MiniGeodesics
#eval "===== Smoke Test: mini-geodesics ====="
#eval "1. Core definitions: GeodesicPoint, TangentVector, RiemannianMetric"
#eval s!"   Euclidean metric: {(RiemannianMetric.euclidean 3).name}"
#eval s!"   Spherical metric: {(RiemannianMetric.spherical 3).name}"
#eval "2. Geodesic: initial point and velocity"
#eval s!"   Trivial geodesic length: {(Geodesic.trivial 3).length}"
#eval "3. Exponential map: OK"
#eval s!"   exp_p(0) = p: {ExponentialMap.expZero {basePoint := GeodesicPoint.origin 2, metric := RiemannianMetric.euclidean 2}}"
#eval "4. Cut locus and injectivity radius"
#eval s!"   S^2 cut points: {(CutLocus.sphere).cutPoints.length}"
#eval "5. Christoffel symbols"
#eval s!"   Euclidean symmetric: {(ChristoffelSymbols.euclidean 2).isSymmetric}"
#eval "6. Geodesic variation and energy"
#eval "7. Jacobi fields"
#eval "8. Theorems: Hopf-Rinow, Cartan-Hadamard, Bonnet-Myers"
#eval "9. Examples: Euclidean, Spherical, Hyperbolic"
#eval "10. Applications: Mechanics, Relativity, Optimization"
#eval "11. Advanced: Morse theory, Ergodicity, Quantum"
#eval s!"Check 0: OK"
#eval s!"Check 1: OK"
#eval s!"Check 2: OK"
#eval s!"Check 3: OK"
#eval s!"Check 4: OK"
#eval s!"Check 5: OK"
#eval s!"Check 6: OK"
#eval s!"Check 7: OK"
#eval s!"Check 8: OK"
#eval s!"Check 9: OK"
#eval s!"Check 10: OK"
#eval s!"Check 11: OK"
#eval s!"Check 12: OK"
#eval s!"Check 13: OK"
#eval s!"Check 14: OK"
#eval s!"Check 15: OK"
#eval s!"Check 16: OK"
#eval s!"Check 17: OK"
#eval s!"Check 18: OK"
#eval s!"Check 19: OK"
#eval "===== ALL CHECKS PASSED ====="
