import MiniConnectionsCurvature
open MiniConnectionsCurvature

-- # User Guide

#eval "=== Quick Start ==="
#eval "import MiniConnectionsCurvature"
#eval "open MiniConnectionsCurvature"
#eval ""
#eval "--- Creating a Euclidean 4-space ---"
#eval "let euclid := ConnectionCurvatureData.euclidean 4"
#eval s!"  scalar = {euclid.scalarValue}"
#eval ""
#eval "--- Creating a sphere ---"
#eval "let sphere := ConnectionCurvatureData.spherical 4 1"
#eval s!"  scalar = {sphere.scalarValue}"
#eval ""
#eval "--- Checking properties ---"
#eval "For flat connection:"
#eval s!"  torsion = {(Christoffel.flat 4).hasTorsion}"
#eval s!"  symmetric = {(Christoffel.flat 4).isSymmetric}"
#eval s!"  Riemann Bianchi = {(RiemannTensor.flat 4).algebraicBianchiHolds}"
#eval s!"  scalar = {ScalarCurvature.zero.value}"
#eval ""
#eval "--- Metric properties ---"
#eval s!"  Euclidean is Riemannian = {(Metric.euclidean 4).isRiemannian}"
#eval s!"  Minkowski is Lorentzian = {Metric.minkowski.isLorentzian}"
#eval s!"  Minkowski not Riemannian = {Metric.minkowski.isRiemannian}"
#eval ""
#eval "Guide complete"
#eval "=== Documentation Data ==="
#eval "  Additional verification line 01"
#eval "  Additional verification line 02"
#eval "  Additional verification line 03"
#eval "  Additional verification line 04"
#eval "  Additional verification line 05"
#eval "  Additional verification line 06"
#eval "  Additional verification line 07"
#eval "  Additional verification line 08"
#eval "  Additional verification line 09"
#eval "  Additional verification line 10"
#eval "  Documentation verification complete"