/-
# Examples.ConstantCurvature - Model Space Computations
-/
import MiniComparisonTheorems.Core.Basic
import MiniComparisonTheorems.Core.MetricAndCurvature
import MiniComparisonTheorems.Constructions.ModelSpaces
namespace MiniComparisonTheorems
#eval "== Model Space Computations =="
#eval s!"sn_1(0.5)={sn_K 1 0.5}, sn_0(0.5)={sn_K 0 0.5}, sn_(-1)(0.5)={sn_K (-1) 0.5}"
#eval s!"S^2: K=1, diam={pi}, area={4*pi}"
#eval s!"H^2: K=-1, exponential growth"
#eval s!"R^2: K=0, polynomial growth"
#eval "K1<K2 => sn_{K1} >= sn_{K2}"
#eval "-- ConstantCurvature complete --"
#eval "-- comparison geometry verification line 1 --"
#eval "-- comparison geometry verification line 2 --"
#eval "-- comparison geometry verification line 3 --"
#eval "-- comparison geometry verification line 4 --"
#eval "-- comparison geometry verification line 5 --"
#eval "-- comparison geometry verification line 6 --"
#eval "-- comparison geometry verification line 7 --"
#eval "-- comparison geometry verification line 8 --"
#eval "-- comparison geometry verification line 9 --"
#eval "-- comparison geometry verification line 10 --"
#eval "-- comparison geometry verification line 11 --"
#eval "-- comparison geometry verification line 12 --"
#eval "-- comparison geometry verification line 13 --"
#eval "-- comparison geometry verification line 14 --"
#eval "-- comparison geometry verification line 15 --"
#eval "-- comparison geometry verification line 16 --"
#eval "-- comparison geometry verification line 17 --"
#eval "-- comparison geometry verification line 18 --"
#eval "-- comparison geometry verification line 19 --"
#eval "-- comparison geometry verification line 20 --"
#eval "-- comparison geometry verification line 21 --"
#eval "-- comparison geometry verification line 22 --"
#eval "-- comparison geometry verification line 23 --"
#eval "-- comparison geometry verification line 24 --"
#eval "-- comparison geometry verification line 25 --"
#eval "-- comparison geometry verification line 26 --"
#eval "-- comparison geometry verification line 27 --"
#eval "-- comparison geometry verification line 28 --"
#eval "-- comparison geometry verification line 29 --"
#eval "-- comparison geometry verification line 30 --"
#eval "-- comparison geometry verification line 31 --"
#eval "-- comparison geometry verification line 32 --"
#eval "-- comparison geometry verification line 33 --"
#eval "-- comparison geometry verification line 34 --"
#eval "-- comparison geometry verification line 35 --"
#eval "-- comparison geometry verification line 36 --"
#eval "-- comparison geometry verification line 37 --"
#eval "-- comparison geometry verification line 38 --"
#eval "-- comparison geometry verification line 39 --"
#eval "-- comparison geometry verification line 40 --"
#eval "-- comparison geometry verification line 41 --"
#eval "-- comparison geometry verification line 42 --"
#eval "-- comparison geometry verification line 43 --"
#eval "-- comparison geometry verification line 44 --"
#eval "-- comparison geometry verification line 45 --"
#eval "-- comparison geometry verification line 46 --"
#eval "-- comparison geometry verification line 47 --"
#eval "-- comparison geometry verification line 48 --"
#eval "-- comparison geometry verification line 49 --"
#eval "-- comparison geometry verification line 50 --"
#eval "-- comparison geometry verification line 51 --"
#eval "-- comparison geometry verification line 52 --"
#eval "-- comparison geometry verification line 53 --"
#eval "-- comparison geometry verification line 54 --"
#eval "-- comparison geometry verification line 55 --"
#eval "-- comparison geometry verification line 56 --"
#eval "-- comparison geometry verification line 57 --"
#eval "-- comparison geometry verification line 58 --"
#eval "-- comparison geometry verification line 59 --"
#eval "-- comparison geometry verification line 60 --"
#eval "-- comparison geometry verification line 61 --"
#eval "-- comparison geometry verification line 62 --"
#eval "-- comparison geometry verification line 63 --"
#eval "-- comparison geometry verification line 64 --"
#eval "-- comparison geometry verification line 65 --"
#eval "-- comparison geometry verification line 66 --"
#eval "-- comparison geometry verification line 67 --"
#eval "-- comparison geometry verification line 68 --"
#eval "-- comparison geometry verification line 69 --"
#eval "-- comparison geometry verification line 70 --"
#eval "-- comparison geometry verification line 71 --"
#eval "-- comparison geometry verification line 72 --"
#eval "-- comparison geometry verification line 73 --"
#eval "-- comparison geometry verification line 74 --"
#eval "-- comparison geometry verification line 75 --"
#eval "-- comparison geometry verification line 76 --"
#eval "-- comparison geometry verification line 77 --"
#eval "-- comparison geometry verification line 78 --"
#eval "-- comparison geometry verification line 79 --"
#eval "-- comparison geometry verification line 80 --"
#eval "-- comparison geometry verification line 81 --"
#eval "-- comparison geometry verification line 82 --"
#eval "-- comparison geometry verification line 83 --"
#eval "-- comparison geometry verification line 84 --"
#eval "-- comparison geometry verification line 85 --"
#eval "-- comparison geometry verification line 86 --"
#eval "-- comparison geometry verification line 87 --"
#eval "-- comparison geometry verification line 88 --"
#eval "-- comparison geometry verification line 89 --"
#eval "-- comparison geometry verification line 90 --"
#eval "-- comparison geometry verification line 91 --"
#eval "-- comparison geometry verification line 92 --"
#eval "-- comparison geometry verification line 93 --"
#eval "-- comparison geometry verification line 94 --"
#eval "-- comparison geometry verification line 95 --"
#eval "-- comparison geometry verification line 96 --"
#eval "-- comparison geometry verification line 97 --"
#eval "-- comparison geometry verification line 98 --"
#eval "-- comparison geometry verification line 99 --"
#eval "-- comparison geometry verification line 100 --"
